apiVersion: 1

datasources:
  - name: Inspection SQLite
    uid: sqlite-inspection
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /opt/web-data/results/_grafana/inspection_metrics.db
